workflows:
  unity-build:
    name: Unity Build - ThunderRealm
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      unity: 2022.3.62f1
      vars:
        BUILD_PLATFORM: android
      groups:
        - unity_credentials  
    scripts:
      - name: Activate Unity license
        script: |
          echo "Activating Unity license..."
          "$UNITY_HOME/Contents/MacOS/Unity" -batchmode \
            -quit \
            -logFile unity_license.log \
            -serial $UNITY_SERIAL \
            -username $UNITY_EMAIL \
            -password $UNITY_PASSWORD

      - name: Prepare Android keystore
        script: |
          echo "Decoding Android keystore..."
          echo $CM_KEYSTORE_BASE64 | base64 --decode > ThunderRealm.keystore
          export ANDROID_KEYSTORE_PATH=ThunderRealm.keystore
          export ANDROID_KEYSTORE_PASSWORD=$CM_KEYSTORE_PASSWORD
          export ANDROID_KEY_ALIAS=$CM_KEY_ALIAS
          export ANDROID_KEY_PASSWORD=$CM_KEY_PASSWORD
          echo "Keystore saved at $ANDROID_KEYSTORE_PATH"

      - name: Build the project
        script: |
          echo "Building Unity project..."
          "$UNITY_HOME/Contents/MacOS/Unity" -batchmode \
            -quit \
            -logFile unity_build.log \
            -projectPath . \
            -executeMethod BuildScript.PerformBuild \
            -nographics
      - name: Return (deactivate) Unity license
        script: |
          echo "Returning Unity license..."
          "$UNITY_HOME/Contents/MacOS/Unity" \
          -batchmode -quit -returnLicense || true

    artifacts:
      - ThunderRealm.aab
      - ThunderRealm.apk
      - unity_build.log
      - unity_license.log
